#! /bin/bash

tagfile=${1:-/dev/stdout}
shift
branch=${1:-master}
shift


echo "" > $tagfile
echo "# automatically generated by $0" >> $tagfile
echo "# this is just a list of the tags that have been applied to the ${branch} branch" >> $tagfile
echo "# incase something terrible happens and the tags are lost." >> $tagfile
echo "# use the retag.sh script to reapply these tags if needed." >> $tagfile

git log --simplify-by-decoration --decorate --pretty=oneline ${branch} | fgrep 'tag: ' | sed "s/ (.*tag: /-/"  | sed "s/[,)] .*$//" | sed "s/-/ /"  >> $tagfile
